# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'XUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Resource_all import *
from functools import cache


@cache
class Ui_MainWindow(object):    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1001, 792)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(70, 39, 900, 700))
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255,0%);")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(50, 40, 800, 600))
        self.label.setStyleSheet(
            "\n""background-image: url(:/Background/photo-1483728642387-6c3bdd6c93e5.jpg);\n""border-radius:20px;\n""")
        self.label.setText("")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(65, 90, 770, 541))
        self.label_2.setStyleSheet(
            "background-color:rgba(0,0,0,100);\n""border-radius:20px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.Exit_button = QtWidgets.QPushButton(self.widget)
        self.Exit_button.setGeometry(QtCore.QRect(795, 54, 40, 30))
        self.Exit_button.setStyleSheet(
            "background-color: rgb(255, 255, 255,0%);")
        self.Exit_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/cancel-1518585.svg"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Exit_button.setIcon(icon)
        self.Exit_button.setIconSize(QtCore.QSize(40, 30))
        self.Exit_button.setObjectName("Exit_button")
        self.Minimize_button = QtWidgets.QPushButton(self.widget)
        self.Minimize_button.setGeometry(QtCore.QRect(750, 54, 40, 30))
        self.Minimize_button.setStyleSheet(
            "background-color: rgb(255, 255, 255,0%);")
        self.Minimize_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(
            ":/Icons/arrow-drop-down-circle-1518593.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Minimize_button.setIcon(icon1)
        self.Minimize_button.setIconSize(QtCore.QSize(40, 30))
        self.Minimize_button.setObjectName("Minimize_button")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(325, 50, 250, 31))
        self.label_3.setStyleSheet(
            "font: 20pt \"Algerian\";\n""color: rgb(0, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.link_text = QtWidgets.QLineEdit(self.widget)
        self.link_text.setGeometry(QtCore.QRect(225, 180, 500, 30))
        self.link_text.setStyleSheet(
            "background-color: rgb(255, 255, 255,0%);\n""font: 87 9pt \"Arial Black\";\n""color: rgb(255, 255, 255);\n""border-bottom:2px solid red;\n""border-radius:0px;")
        self.link_text.setObjectName("link_text")
        self.Audio_button = QtWidgets.QRadioButton(self.widget)
        self.Audio_button.setGeometry(QtCore.QRect(300, 240, 81, 20))
        self.Audio_button.setStyleSheet(
            "font: 75 8pt \"8514oem\";\n""color: rgb(0, 255, 0);")
        self.Audio_button.setObjectName("Audio_button")
        self.Video_low_button = QtWidgets.QRadioButton(self.widget)
        self.Video_low_button.setGeometry(QtCore.QRect(300, 280, 231, 20))
        self.Video_low_button.setStyleSheet(
            "font: 75 8pt \"8514oem\";\n""color: rgb(170, 85, 255);")
        self.Video_low_button.setObjectName("Video_low_button")
        self.Video_high_button = QtWidgets.QRadioButton(self.widget)
        self.Video_high_button.setGeometry(QtCore.QRect(300, 320, 241, 20))
        self.Video_high_button.setStyleSheet(
            "font: 75 8pt \"8514oem\";\n""color: rgb(170, 85, 255);")
        self.Video_high_button.setObjectName("Video_high_button")
        self.Path_text = QtWidgets.QLineEdit(self.widget)
        self.Path_text.setGeometry(QtCore.QRect(225, 380, 500, 30))
        self.Path_text.setStyleSheet(
            "background-color: rgb(255, 255, 255,0%);\n""color: rgb(255, 255, 255);\n""font: 87 9pt \"Arial Black\";\n""border-bottom:2px solid blue;\n""border-radius:0px;")
        self.Path_text.setObjectName("Path_text")
        self.Download_button = QtWidgets.QPushButton(self.widget)
        self.Download_button.setGeometry(QtCore.QRect(390, 450, 161, 30))
        self.Download_button.setStyleSheet("QPushButton {\n"" \n""    font: 87 10pt \"Arial Black\";\n""    \n""    color: rgb(170, 255, 0);\n""    \n""    background-color: rgb(255, 255, 255,0%);\n""    border:3px solid rgb(255, 0, 0);\n""    border-radius:10px;\n""}\n""QPushButton:hover {\n"
                                           "    font: 87 10pt \"Arial Black\";\n"
                                           "    \n"
                                           "    color: rgb(170, 255, 0);\n"
                                           "    \n"
                                           "    background-color:rgb(170, 170, 127,50%);\n"
                                           "    border:3px solid rgb(255, 0, 0);\n"
                                           "    border-radius:10px;\n"
                                           "}\n"
                                           "QPushButton:pressed {\n"
                                           "    font: 87 10pt \"Arial Black\";\n"
                                           "    \n"
                                           "    color: rgb(170, 255, 0);\n"
                                           "    \n"
                                           "    background-color:rgb(255, 0, 0,50%);\n"
                                           "    border:3px solid rgb(255, 0, 0);\n"
                                           "    border-radius:10px;\n"
                                           "}\n"
                                           "")
        self.Download_button.setObjectName("Download_button")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(80, 60, 171, 21))
        self.label_4.setStyleSheet("font: 10pt \"Algerian\";\n"
                                   "color: rgb(170, 255, 127);")
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "PI DOWNLOADER"))
        self.link_text.setPlaceholderText(_translate(
            "MainWindow", "Paste the Video or Playlist link"))
        self.Audio_button.setText(_translate("MainWindow", "Audio "))
        self.Video_low_button.setText(_translate(
            "MainWindow", "Video Low Resolution"))
        self.Video_high_button.setText(_translate(
            "MainWindow", "Video High Resolution"))
        self.Path_text.setPlaceholderText(_translate(
            "MainWindow", "Enter the Path where video will be saved"))
        self.Download_button.setText(_translate("MainWindow", "Download"))
        self.label_4.setText(_translate("MainWindow", "Version 2.0"))
         



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
